### ISSUE TITLE
New Feature: Accomodate device IP address changes

### ISSUE THREAD

**Issue by sanjarcode** [dengzii/WiFiADB#26]
It can be observed that going 'Airplane mode' or restarting the device changes the IP adress.

Approaches
1. Use a cable and set device. - **This is a pain.**
2. Reconfigure the plugin: Go to *tools* --> *WifiADB* --> *Main* --> *Connect Manual*. Lookup the new IP address in the device. Then enter it in the box. -  **This approach fails.**
![image](https://user-images.githubusercontent.com/48156230/103848752-1cfe2b80-50c9-11eb-905e-6428ed40d80d.png)

My device reboots every alternate night, so IP address is bound to change. Can't we just set the IP address from the active hotspot using ifconfig or somethinh. This would be really helpful, as it'd never require a USB cable, except when the plugin is installed.

**Comment by dengzii** [comment]
Hi, 
If the devices not config static IP or the WiFi router not config bind IP to MAC, the IP address may change every time you connect WiFi. presume from your IP address that you are using a WAN rather than a LAN, so your IP address will change every time when you reconnect to the internet.

`Connect Manual` failed may well the device closed the ADB port 5555, some devices close the ADB port when ADB Debug disconnected(or restart device), this is a problem that can't be solved.

The only way to completely get rid of USB cable is to let devices tell computer itself's IP address and ADB port, this is complex, this feature cannot be implemented.

**Comment by sanjarcode** [comment]
Got it. Label this issue as a won't fix.
Thanks for the plugin.
I'm closing the issue.
