### ISSUE TITLE
Why does it show an alert about license?

### ISSUE THREAD

**Issue by AndkePxn** [dengzii/WiFiADB#47]
When i open this plugin in Android studio Arctic fox patch 3, it show an alert about not having license first, close it and then you can use this plugin, why is that?

**Comment by dengzii** [comment]
Because now ave a payment option, but some version of AndroidStudio don't support `JetBrains MarketPlace License`, so the 
 IDE build in active Dialog cannot display, but it does not affect normal use.

Check for active support: `Help > Register Plugins`, if you do not see this option express not supported.
